name: Feature Request
description: Suggest an idea to improve Cider.
title: "[Enhancement]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: textarea
    id: description
    attributes:
      label: The feature you would like
      description: A clear and concise description of what you would like to be added to the application. State if your request if related to an issue.
      placeholder: A great addition to this project would be...
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Alternatives and Other Information
      description: If you have any alternative solutions to implement your request or other information that could help.
      placeholder: Anything that can help us?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
